import { DeliveryPricingSettings, LocationItem, Merchant, Parcel, Rider, SettlementRequest, SupportTicket, CompanySettings, LedgerTransaction, AuditLog } from '../types';

export const DEFAULT_PRICING: DeliveryPricingSettings = {
  insideDhaka: 120, // Default requested: ৳120 Inside Dhaka
  outsideDhaka: 180,
  expressDhaka: 180,
  subDhaka: 150,
  codPercentageFee: 0.01, // 1% COD charge
  returnChargeInsideDhaka: 60,
  returnChargeOutsideDhaka: 90,
};

export const DEFAULT_COMPANY_SETTINGS: CompanySettings = {
  companyName: 'FISHORA Express',
  tagline: 'Fast Delivery. Trusted Service.',
  hotline: '+880 9612-445566',
  supportEmail: 'support@fishoraexpress.com.bd',
  headOfficeAddress: 'House 14, Road 7, Block D, Niketon, Gulshan-1, Dhaka-1212, Bangladesh',
  bkashMerchantNumber: '01811-000000',
  nagadMerchantNumber: '01711-000000',
  enableSmsNotifications: true,
  enableEmailNotifications: true,
  systemStatus: 'online',
};

export const DHAKA_AREAS = [
  'Mirpur',
  'Uttara',
  'Dhanmondi',
  'Mohammadpur',
  'Gulshan',
  'Banani',
  'Badda',
  'Rampura',
  'Motijheel',
  'Jatrabari',
  'Farmgate',
  'Tejgaon',
  'Bashundhara R/A',
  'Khilgaon',
  'Malibagh',
  'Mohakhali',
  'Shantinagar',
  'Moghbazar',
  'Old Dhaka (Sadarghat)',
  'Lalbagh',
  'Hazaribagh',
  'Pallabi',
  'Kafrul',
  'Cantonment',
  'Baridhara',
  'Nikunja',
  'Khilkhet',
  'Azimpur',
  'Shahbagh',
  'Savar',
  'Keraniganj',
  'Tongir Mor',
  'Ashulia',
  'Gazipur Sadar',
  'Narayanganj City',
];

export const BANGLADESH_DISTRICTS = [
  'Dhaka',
  'Chittagong',
  'Sylhet',
  'Rajshahi',
  'Khulna',
  'Barisal',
  'Rangpur',
  'Mymensingh',
  'Comilla',
  'Gazipur',
  'Narayanganj',
  'Brahmanbaria',
  'Bogra',
  'Jessore',
  'Cox\'s Bazar',
  'Tangail',
  'Dinajpur',
  'Narsingdi',
  'Faridpur',
  'Pabna',
  'Noakhali',
  'Kushtia',
  'Feni',
];

export const INITIAL_LOCATIONS: LocationItem[] = [
  // Dhaka Areas
  { id: 'loc-1', division: 'Dhaka', district: 'Dhaka', area: 'Mirpur', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-2', division: 'Dhaka', district: 'Dhaka', area: 'Uttara', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-3', division: 'Dhaka', district: 'Dhaka', area: 'Dhanmondi', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-4', division: 'Dhaka', district: 'Dhaka', area: 'Mohammadpur', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-5', division: 'Dhaka', district: 'Dhaka', area: 'Gulshan', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-6', division: 'Dhaka', district: 'Dhaka', area: 'Banani', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-7', division: 'Dhaka', district: 'Dhaka', area: 'Badda', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-8', division: 'Dhaka', district: 'Dhaka', area: 'Rampura', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-9', division: 'Dhaka', district: 'Dhaka', area: 'Motijheel', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-10', division: 'Dhaka', district: 'Dhaka', area: 'Jatrabari', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-11', division: 'Dhaka', district: 'Dhaka', area: 'Farmgate', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-12', division: 'Dhaka', district: 'Dhaka', area: 'Tejgaon', isInsideDhaka: true, deliveryCharge: 120, estimatedHours: 24, isActive: true },
  { id: 'loc-13', division: 'Dhaka', district: 'Dhaka', area: 'Savar', isInsideDhaka: false, deliveryCharge: 150, estimatedHours: 36, isActive: true },
  { id: 'loc-14', division: 'Dhaka', district: 'Dhaka', area: 'Keraniganj', isInsideDhaka: false, deliveryCharge: 150, estimatedHours: 36, isActive: true },
  // Outside Dhaka Major Hubs
  { id: 'loc-15', division: 'Chittagong', district: 'Chittagong', area: 'Agrabad / GEC Circle', isInsideDhaka: false, deliveryCharge: 180, estimatedHours: 48, isActive: true },
  { id: 'loc-16', division: 'Sylhet', district: 'Sylhet', area: 'Zindabazar / Subidbazar', isInsideDhaka: false, deliveryCharge: 180, estimatedHours: 48, isActive: true },
  { id: 'loc-17', division: 'Rajshahi', district: 'Rajshahi', area: 'Shaheb Bazar', isInsideDhaka: false, deliveryCharge: 180, estimatedHours: 48, isActive: true },
  { id: 'loc-18', division: 'Khulna', district: 'Khulna', area: 'Shibbari / Daulatpur', isInsideDhaka: false, deliveryCharge: 180, estimatedHours: 48, isActive: true },
];

export const INITIAL_MERCHANTS: Merchant[] = [
  {
    id: 'MRC-0001',
    businessName: 'FISHORA Mart',
    ownerName: 'Rafiqul Islam',
    phone: '01712-345678',
    email: 'merchant@fishora.com',
    address: 'House 42, Road 11, Block E, Banani, Dhaka',
    district: 'Dhaka',
    area: 'Banani',
    status: 'active',
    paymentMethod: 'bkash',
    paymentNumberOrAccount: '01712-345678',
    nidOrTradeLicense: 'TRD-DHK-992140',
    currentBalance: 4680,
    createdAt: '2026-05-10T10:00:00Z',
    approvedAt: '2026-05-10T11:30:00Z',
  },
  {
    id: 'MRC-0002',
    businessName: 'Quick Shop BD',
    ownerName: 'Nusrat Jahan',
    phone: '01819-223344',
    email: 'nusrat@quickshop.bd',
    address: 'Plot 12, Sector 3, Uttara, Dhaka',
    district: 'Dhaka',
    area: 'Uttara',
    status: 'pending',
    paymentMethod: 'nagad',
    paymentNumberOrAccount: '01819-223344',
    nidOrTradeLicense: 'NID-8829104921',
    currentBalance: 0,
    createdAt: '2026-08-25T09:15:00Z',
  },
  {
    id: 'MRC-0003',
    businessName: 'Best Electronics',
    ownerName: 'Imran Hossain',
    phone: '01911-556677',
    email: 'imran@bestelectronics.com',
    address: 'Shop 104, Multiplan Center, Elephant Road, Dhaka',
    district: 'Dhaka',
    area: 'Dhanmondi',
    status: 'active',
    paymentMethod: 'bank',
    paymentNumberOrAccount: '20501180200192',
    bankName: 'Islami Bank Bangladesh Ltd',
    bankBranch: 'Dhanmondi Branch',
    routingNumber: '125261400',
    currentBalance: 8200,
    createdAt: '2026-06-01T14:20:00Z',
    approvedAt: '2026-06-01T16:00:00Z',
  },
  {
    id: 'MRC-0004',
    businessName: 'Fashion Point BD',
    ownerName: 'Farzana Akter',
    phone: '01611-998877',
    email: 'farzana@fashionpoint.com',
    address: 'Level 3, Police Plaza Concord, Gulshan 1, Dhaka',
    district: 'Dhaka',
    area: 'Gulshan',
    status: 'suspended',
    paymentMethod: 'bkash',
    paymentNumberOrAccount: '01611-998877',
    currentBalance: 1200,
    createdAt: '2026-05-18T12:00:00Z',
    approvedAt: '2026-05-19T09:00:00Z',
  },
  {
    id: 'MRC-0005',
    businessName: 'Daily Organic Needs',
    ownerName: 'Tanjim Ahmed',
    phone: '01755-443322',
    email: 'tanjim@dailyorganic.bd',
    address: 'Lane 4, Mirpur DOHS, Dhaka',
    district: 'Dhaka',
    area: 'Mirpur',
    status: 'active',
    paymentMethod: 'bkash',
    paymentNumberOrAccount: '01755-443322',
    currentBalance: 3150,
    createdAt: '2026-07-15T08:30:00Z',
    approvedAt: '2026-07-15T10:00:00Z',
  }
];

export const INITIAL_RIDERS: Rider[] = [
  {
    id: 'RDR-101',
    name: 'Tanvir Hossain',
    phone: '01788-112233',
    email: 'tanvir.rider@fishora.com',
    address: 'Mirpur 10, Dhaka',
    assignedArea: 'Mirpur',
    zone: 'Mirpur & Dhanmondi, Dhaka',
    status: 'active',
    vehicleType: 'motorcycle',
    totalDelivered: 142,
    totalCollectedCOD: 185000,
    createdAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'RDR-102',
    name: 'Sajib Mia',
    phone: '01899-445566',
    email: 'sajib.rider@fishora.com',
    address: 'Sector 7, Uttara, Dhaka',
    assignedArea: 'Uttara',
    zone: 'Uttara & Airport, Dhaka',
    status: 'active',
    vehicleType: 'motorcycle',
    totalDelivered: 98,
    totalCollectedCOD: 124000,
    createdAt: '2026-04-15T08:00:00Z',
  },
  {
    id: 'RDR-103',
    name: 'Kamrul Hasan',
    phone: '01677-778899',
    email: 'kamrul.rider@fishora.com',
    address: 'Dhanmondi 27, Dhaka',
    assignedArea: 'Dhanmondi',
    zone: 'Dhanmondi & Mohammadpur, Dhaka',
    status: 'active',
    vehicleType: 'motorcycle',
    totalDelivered: 110,
    totalCollectedCOD: 156000,
    createdAt: '2026-05-01T08:00:00Z',
  },
  {
    id: 'RDR-104',
    name: 'Mehedi Hasan',
    phone: '01922-334455',
    email: 'mehedi.rider@fishora.com',
    address: 'Gulshan 2, Dhaka',
    assignedArea: 'Gulshan',
    zone: 'Gulshan & Banani, Dhaka',
    status: 'active',
    vehicleType: 'motorcycle',
    totalDelivered: 85,
    totalCollectedCOD: 98500,
    createdAt: '2026-05-15T08:00:00Z',
  }
];

export const INITIAL_PARCELS: Parcel[] = [
  {
    id: 'FX-100254',
    trackingId: 'FX-TRK-100254',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    merchantPhone: '01712-345678',
    pickupAddress: 'House 42, Road 11, Block E, Banani, Dhaka',
    customerName: 'Rafiq Hasan',
    customerPhone: '01812-998811',
    district: 'Dhaka',
    area: 'Mirpur',
    fullAddress: 'House 24, Road 4, Section 6, Mirpur, Dhaka',
    deliveryNote: 'Call 15 minutes before arrival',
    productName: 'Premium Cotton Polo Shirt (XL)',
    quantity: 2,
    weight: 0.6,
    parcelType: 'clothing',
    deliveryType: 'inside_dhaka',
    codAmount: 1200,
    deliveryCharge: 120,
    codCharge: 12,
    merchantPayable: 1068,
    isCodCollected: false,
    settlementStatus: 'unsettled',
    status: 'in_transit',
    assignedRiderId: 'RDR-101',
    assignedRiderName: 'Tanvir Hossain',
    assignedRiderPhone: '01788-112233',
    createdAt: '2026-08-25T10:30:00Z',
    updatedAt: '2026-08-26T06:45:00Z',
    estimatedDeliveryDate: '2026-08-27',
    trackingHistory: [
      { id: 'th-1', status: 'pending', title: 'Parcel Created', description: 'Merchant placed delivery order', location: 'Banani Hub', timestamp: '2026-08-25T10:30:00Z', updatedBy: 'FISHORA Mart' },
      { id: 'th-2', status: 'pickup_assigned', title: 'Pickup Assigned', description: 'Assigned to Rider Tanvir Hossain', location: 'Dhaka North Hub', timestamp: '2026-08-25T12:00:00Z', updatedBy: 'Admin Dispatch' },
      { id: 'th-3', status: 'picked_up', title: 'Picked Up', description: 'Rider picked parcel from merchant warehouse', location: 'Banani, Dhaka', timestamp: '2026-08-25T15:20:00Z', updatedBy: 'Tanvir Hossain (Rider)' },
      { id: 'th-4', status: 'in_transit', title: 'In Transit', description: 'Parcel is on way to Mirpur sorting sub-hub', location: 'Tejgaon Sorting Hub', timestamp: '2026-08-26T06:45:00Z', updatedBy: 'Tejgaon Hub Admin' }
    ]
  },
  {
    id: 'FX-100253',
    trackingId: 'FX-TRK-100253',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    merchantPhone: '01712-345678',
    pickupAddress: 'House 42, Road 11, Block E, Banani, Dhaka',
    customerName: 'Nusrat Jahan',
    customerPhone: '01777-334422',
    district: 'Dhaka',
    area: 'Uttara',
    fullAddress: 'House 18, Road 12, Sector 4, Uttara, Dhaka',
    deliveryNote: 'Gate code 4022',
    productName: 'Organic Honey & Black Seed Oil',
    quantity: 1,
    weight: 1.0,
    parcelType: 'regular',
    deliveryType: 'inside_dhaka',
    codAmount: 850,
    deliveryCharge: 120,
    codCharge: 8.5,
    merchantPayable: 721.5,
    isCodCollected: false,
    settlementStatus: 'unsettled',
    status: 'out_for_delivery',
    assignedRiderId: 'RDR-102',
    assignedRiderName: 'Sajib Mia',
    assignedRiderPhone: '01899-445566',
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-08-26T09:30:00Z',
    estimatedDeliveryDate: '2026-08-26',
    trackingHistory: [
      { id: 'th-21', status: 'pending', title: 'Parcel Created', description: 'Order recorded', location: 'Banani', timestamp: '2026-08-25T11:00:00Z', updatedBy: 'FISHORA Mart' },
      { id: 'th-22', status: 'picked_up', title: 'Picked Up', description: 'Picked up by hub', location: 'Dhaka', timestamp: '2026-08-25T16:00:00Z', updatedBy: 'Hub Staff' },
      { id: 'th-23', status: 'out_for_delivery', title: 'Out for Delivery', description: 'Rider Sajib Mia is on the way to deliver', location: 'Uttara Hub', timestamp: '2026-08-26T09:30:00Z', updatedBy: 'Sajib Mia (Rider)' }
    ]
  },
  {
    id: 'FX-100252',
    trackingId: 'FX-TRK-100252',
    merchantId: 'MRC-0003',
    merchantName: 'Best Electronics',
    merchantPhone: '01911-556677',
    pickupAddress: 'Shop 104, Multiplan Center, Elephant Road, Dhaka',
    customerName: 'Imran Hossain',
    customerPhone: '01655-443322',
    district: 'Dhaka',
    area: 'Dhanmondi',
    fullAddress: 'Flat 4B, Road 8/A, Dhanmondi, Dhaka',
    productName: 'Mechanical Gaming Keyboard RGB',
    quantity: 1,
    weight: 1.2,
    parcelType: 'electronics',
    deliveryType: 'inside_dhaka',
    codAmount: 2650,
    deliveryCharge: 120,
    codCharge: 26.5,
    merchantPayable: 2503.5,
    isCodCollected: false,
    settlementStatus: 'unsettled',
    status: 'pending',
    createdAt: '2026-08-26T08:00:00Z',
    updatedAt: '2026-08-26T08:00:00Z',
    estimatedDeliveryDate: '2026-08-27',
    trackingHistory: [
      { id: 'th-31', status: 'pending', title: 'Parcel Created', description: 'Waiting for pickup confirmation', location: 'Elephant Road', timestamp: '2026-08-26T08:00:00Z', updatedBy: 'Best Electronics' }
    ]
  },
  {
    id: 'FX-100251',
    trackingId: 'FX-TRK-100251',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    merchantPhone: '01712-345678',
    pickupAddress: 'House 42, Road 11, Block E, Banani, Dhaka',
    customerName: 'Farzana Akter',
    customerPhone: '01888-221199',
    district: 'Dhaka',
    area: 'Mohammadpur',
    fullAddress: 'Block C, Tajmahal Road, Mohammadpur, Dhaka',
    productName: 'Handloom Cotton Saree',
    quantity: 1,
    weight: 0.8,
    parcelType: 'clothing',
    deliveryType: 'inside_dhaka',
    codAmount: 1500,
    deliveryCharge: 120,
    codCharge: 15,
    merchantPayable: 1365,
    isCodCollected: true,
    settlementStatus: 'settled',
    settlementId: 'STL-9001',
    status: 'delivered',
    assignedRiderId: 'RDR-103',
    assignedRiderName: 'Kamrul Hasan',
    assignedRiderPhone: '01677-778899',
    createdAt: '2026-08-23T10:00:00Z',
    updatedAt: '2026-08-24T14:15:00Z',
    estimatedDeliveryDate: '2026-08-24',
    deliveredAt: '2026-08-24T14:15:00Z',
    trackingHistory: [
      { id: 'th-41', status: 'pending', title: 'Parcel Created', description: 'Order created', location: 'Banani', timestamp: '2026-08-23T10:00:00Z', updatedBy: 'FISHORA Mart' },
      { id: 'th-42', status: 'picked_up', title: 'Picked Up', description: 'Picked up', location: 'Dhaka Hub', timestamp: '2026-08-23T14:00:00Z', updatedBy: 'Kamrul Hasan' },
      { id: 'th-43', status: 'out_for_delivery', title: 'Out for Delivery', description: 'Rider is delivering', location: 'Mohammadpur', timestamp: '2026-08-24T11:00:00Z', updatedBy: 'Kamrul Hasan' },
      { id: 'th-44', status: 'delivered', title: 'Delivered', description: 'Customer accepted parcel and paid ৳1,500 COD', location: 'Tajmahal Road', timestamp: '2026-08-24T14:15:00Z', updatedBy: 'Kamrul Hasan' }
    ]
  },
  {
    id: 'FX-100250',
    trackingId: 'FX-TRK-100250',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    merchantPhone: '01712-345678',
    pickupAddress: 'House 42, Road 11, Block E, Banani, Dhaka',
    customerName: 'Tanjim Ahmed',
    customerPhone: '01711-224466',
    district: 'Dhaka',
    area: 'Gulshan',
    fullAddress: 'Road 53, Gulshan 2, Dhaka',
    productName: 'Leather Laptop Backpack',
    quantity: 1,
    weight: 1.1,
    parcelType: 'regular',
    deliveryType: 'inside_dhaka',
    codAmount: 2000,
    deliveryCharge: 120,
    codCharge: 20,
    merchantPayable: 1860,
    isCodCollected: true,
    settlementStatus: 'unsettled',
    status: 'delivered',
    assignedRiderId: 'RDR-104',
    assignedRiderName: 'Mehedi Hasan',
    assignedRiderPhone: '01922-334455',
    createdAt: '2026-08-24T09:00:00Z',
    updatedAt: '2026-08-25T15:30:00Z',
    estimatedDeliveryDate: '2026-08-25',
    deliveredAt: '2026-08-25T15:30:00Z',
    trackingHistory: [
      { id: 'th-51', status: 'pending', title: 'Parcel Created', description: 'Order created', location: 'Banani', timestamp: '2026-08-24T09:00:00Z', updatedBy: 'FISHORA Mart' },
      { id: 'th-52', status: 'delivered', title: 'Delivered', description: 'Delivered successfully with ৳2,000 cash collected', location: 'Gulshan 2', timestamp: '2026-08-25T15:30:00Z', updatedBy: 'Mehedi Hasan' }
    ]
  },
  {
    id: 'FX-100249',
    trackingId: 'FX-TRK-100249',
    merchantId: 'MRC-0005',
    merchantName: 'Daily Organic Needs',
    merchantPhone: '01755-443322',
    pickupAddress: 'Lane 4, Mirpur DOHS, Dhaka',
    customerName: 'Shakib Islam',
    customerPhone: '01933-889900',
    district: 'Dhaka',
    area: 'Badda',
    fullAddress: 'Middle Badda, Pragati Sarani, Dhaka',
    productName: 'Chia Seeds & Almonds Combo',
    quantity: 1,
    weight: 0.5,
    parcelType: 'regular',
    deliveryType: 'inside_dhaka',
    codAmount: 450,
    deliveryCharge: 120,
    codCharge: 4.5,
    merchantPayable: 325.5,
    isCodCollected: false,
    settlementStatus: 'unsettled',
    status: 'cancelled',
    createdAt: '2026-08-22T14:00:00Z',
    updatedAt: '2026-08-23T11:00:00Z',
    estimatedDeliveryDate: '2026-08-23',
    trackingHistory: [
      { id: 'th-61', status: 'pending', title: 'Parcel Created', description: 'Created', location: 'Mirpur', timestamp: '2026-08-22T14:00:00Z', updatedBy: 'Daily Organic Needs' },
      { id: 'th-62', status: 'cancelled', title: 'Order Cancelled', description: 'Customer cancelled by phone', location: 'Badda', timestamp: '2026-08-23T11:00:00Z', updatedBy: 'Customer Service' }
    ]
  },
  {
    id: 'FX-100248',
    trackingId: 'FX-TRK-100248',
    merchantId: 'MRC-0003',
    merchantName: 'Best Electronics',
    merchantPhone: '01911-556677',
    pickupAddress: 'Shop 104, Multiplan Center, Elephant Road, Dhaka',
    customerName: 'Orpita Saha',
    customerPhone: '01711-667788',
    district: 'Dhaka',
    area: 'Jatrabari',
    fullAddress: 'Doyaganj Moor, Jatrabari, Dhaka',
    productName: 'Fast Charging Power Bank 20000mAh',
    quantity: 1,
    weight: 0.6,
    parcelType: 'electronics',
    deliveryType: 'inside_dhaka',
    codAmount: 750,
    deliveryCharge: 120,
    codCharge: 7.5,
    merchantPayable: 622.5,
    isCodCollected: false,
    settlementStatus: 'unsettled',
    status: 'returned',
    createdAt: '2026-08-21T09:00:00Z',
    updatedAt: '2026-08-23T17:00:00Z',
    estimatedDeliveryDate: '2026-08-22',
    trackingHistory: [
      { id: 'th-71', status: 'pending', title: 'Parcel Created', description: 'Order created', location: 'Elephant Rd', timestamp: '2026-08-21T09:00:00Z', updatedBy: 'Best Electronics' },
      { id: 'th-72', status: 'out_for_delivery', title: 'Out for Delivery', description: 'Customer unreachable after 3 attempts', location: 'Jatrabari', timestamp: '2026-08-22T14:00:00Z', updatedBy: 'Rider Staff' },
      { id: 'th-73', status: 'returned', title: 'Returned to Merchant', description: 'Parcel returned back to merchant warehouse', location: 'Elephant Rd', timestamp: '2026-08-23T17:00:00Z', updatedBy: 'Return Desk' }
    ]
  }
];

export const INITIAL_SETTLEMENTS: SettlementRequest[] = [
  {
    id: 'STL-9001',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    merchantPhone: '01712-345678',
    amount: 1365,
    method: 'bkash',
    accountDetails: '01712-345678 (Personal)',
    transactionReference: 'BKH982310499',
    status: 'paid',
    createdAt: '2026-08-24T18:00:00Z',
    processedAt: '2026-08-25T11:00:00Z',
    adminNote: 'Settlement processed via bKash Merchant auto-disbursement',
    parcelIds: ['FX-100251']
  },
  {
    id: 'STL-9002',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    merchantPhone: '01712-345678',
    amount: 1860,
    method: 'bkash',
    accountDetails: '01712-345678 (Personal)',
    status: 'pending',
    createdAt: '2026-08-26T07:00:00Z',
    adminNote: 'Waiting for weekly finance clearance',
    parcelIds: ['FX-100250']
  },
  {
    id: 'STL-9003',
    merchantId: 'MRC-0003',
    merchantName: 'Best Electronics',
    merchantPhone: '01911-556677',
    amount: 8500,
    method: 'bank',
    accountDetails: 'Islami Bank - A/C 20501180200192',
    status: 'processing',
    createdAt: '2026-08-25T16:00:00Z',
    adminNote: 'BEFTN batch dispatched to bank',
  }
];

export const INITIAL_LEDGER: LedgerTransaction[] = [
  {
    id: 'LED-001',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    parcelId: 'FX-100251',
    type: 'cod_credit',
    amount: 1500,
    description: 'Delivered parcel COD collected: FX-100251',
    date: '2026-08-24T14:15:00Z',
    balanceAfter: 1500
  },
  {
    id: 'LED-002',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    parcelId: 'FX-100251',
    type: 'delivery_fee_debit',
    amount: -120,
    description: 'Inside Dhaka delivery fee: FX-100251',
    date: '2026-08-24T14:15:00Z',
    balanceAfter: 1380
  },
  {
    id: 'LED-003',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    parcelId: 'FX-100251',
    type: 'cod_fee_debit',
    amount: -15,
    description: '1% COD handling fee: FX-100251',
    date: '2026-08-24T14:15:00Z',
    balanceAfter: 1365
  },
  {
    id: 'LED-004',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    type: 'settlement_payout',
    amount: -1365,
    description: 'Disbursed payout STL-9001 via bKash (TrxID: BKH982310499)',
    date: '2026-08-25T11:00:00Z',
    balanceAfter: 0
  },
  {
    id: 'LED-005',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    parcelId: 'FX-100250',
    type: 'cod_credit',
    amount: 2000,
    description: 'Delivered parcel COD collected: FX-100250',
    date: '2026-08-25T15:30:00Z',
    balanceAfter: 2000
  },
  {
    id: 'LED-006',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    parcelId: 'FX-100250',
    type: 'delivery_fee_debit',
    amount: -120,
    description: 'Inside Dhaka delivery fee: FX-100250',
    date: '2026-08-25T15:30:00Z',
    balanceAfter: 1880
  },
  {
    id: 'LED-007',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    parcelId: 'FX-100250',
    type: 'cod_fee_debit',
    amount: -20,
    description: '1% COD handling fee: FX-100250',
    date: '2026-08-25T15:30:00Z',
    balanceAfter: 1860
  }
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-501',
    merchantId: 'MRC-0001',
    merchantName: 'FISHORA Mart',
    merchantPhone: '01712-345678',
    subject: 'Urgent: Customer requested address change for FX-100254',
    category: 'delivery_issue',
    relatedParcelId: 'FX-100254',
    status: 'in_progress',
    createdAt: '2026-08-26T07:30:00Z',
    updatedAt: '2026-08-26T08:00:00Z',
    messages: [
      {
        id: 'msg-1',
        senderRole: 'merchant',
        senderName: 'Rafiqul Islam (FISHORA Mart)',
        message: 'Customer called and requested to deliver to Mirpur 10 instead of Section 6. Please inform rider Tanvir.',
        timestamp: '2026-08-26T07:30:00Z'
      },
      {
        id: 'msg-2',
        senderRole: 'admin',
        senderName: 'Support Agent - Fahim',
        message: 'Noted with priority! Rider Tanvir Hossain has been notified with the updated note.',
        timestamp: '2026-08-26T08:00:00Z'
      }
    ]
  },
  {
    id: 'TCK-502',
    merchantId: 'MRC-0003',
    merchantName: 'Best Electronics',
    merchantPhone: '01911-556677',
    subject: 'Inquiry regarding BEFTN settlement disbursement timeframe',
    category: 'payment_issue',
    status: 'resolved',
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-08-25T14:30:00Z',
    messages: [
      {
        id: 'msg-3',
        senderRole: 'merchant',
        senderName: 'Imran Hossain',
        message: 'When will the STL-9003 bank transfer reflect in our account?',
        timestamp: '2026-08-25T11:00:00Z'
      },
      {
        id: 'msg-4',
        senderRole: 'admin',
        senderName: 'Finance Desk',
        message: 'Bank settlements are processed every banking day at 2:00 PM. It will reflect in your Islami Bank account today by 6:00 PM.',
        timestamp: '2026-08-25T14:30:00Z'
      }
    ]
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-901',
    userId: 'ADM-01',
    userName: 'Head Admin',
    userRole: 'admin',
    action: 'MERCHANT_APPROVED',
    targetType: 'merchant',
    targetId: 'MRC-0001',
    details: 'Approved merchant FISHORA Mart account after NID verification',
    timestamp: '2026-05-10T11:30:00Z'
  },
  {
    id: 'AUD-902',
    userId: 'ADM-01',
    userName: 'Head Admin',
    userRole: 'admin',
    action: 'SETTLEMENT_APPROVED',
    targetType: 'settlement',
    targetId: 'STL-9001',
    details: 'Disbursed ৳1,365 via bKash TrxID: BKH982310499',
    timestamp: '2026-08-25T11:00:00Z'
  },
  {
    id: 'AUD-903',
    userId: 'RDR-101',
    userName: 'Tanvir Hossain',
    userRole: 'rider',
    action: 'STATUS_UPDATED',
    targetType: 'parcel',
    targetId: 'FX-100254',
    details: 'Updated status to IN TRANSIT at Tejgaon Sorting Hub',
    timestamp: '2026-08-26T06:45:00Z'
  }
];
